name: artifacts
on: 
    push:
        branches-ignore: #this workflow will not running in main branchs
        -   main    

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: create artifact
          run: |
                 mkdir -p path/to/artifact
                 echo this is me > path/to/artifact/world.txt
        - uses: actions/upload-artifact@v4
          with:
                name: my-artifact
                path: path/to/artifact/world.txt
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
        - uses: actions/download-artifact@v5
          with:
                name: my-artifact
                path: path/to/artifact
        - name: Display structure of downloaded files
          run: cat path/to/artifact/world.txt