name: test action
on: 
    schedule:
    -  cron: '*/3 * * * *' 
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        -   name: test
            uses: actions/checkout@v3
        -   name: echo date
            run: "echo the time of trigger run $(date -u)"


