name: artifacts
on: [push,workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest  
    steps:
      - name: create file and use it for artifacts
        run: |
          echo "123456" > test1.txt
      - name: use artifacts
        uses: actions/upload-artifact@v5
        with:
          name: test-artifact
          path: test1.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: download artifact
        uses: actions/download-artifact@v5
        with:
          name: test-artifact

      - name: list file
        run: cat test1.txt